apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: onlineeventbooking-shahmeer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-notification
          image: busybox
          command: ['sh', '-c', 'until nc -z notification-service 8004; do echo waiting for Notification Service; sleep 2; done']
      containers:
        - name: frontend
          image: 22i1048/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: event-booking-config

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: onlineeventbooking-shahmeer
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
