apiVersion: v1
kind: Secret
metadata:
  name: event-booking-secrets
  namespace: onlineeventbooking-shahmeer
type: Opaque
data:
  # PostgreSQL User Service
  POSTGRES_USER: "YWRtaW4="  # Base64-encoded "admin"
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="  # Base64-encoded "password"
  POSTGRES_DB_USER: "dXNlcl9zZXJ2aWNl"  # Base64-encoded "user_service"

  # PostgreSQL Booking Service
  POSTGRES_DB_BOOKING: "Ym9va2luZ19zZXJ2aWNl"  # Base64-encoded "booking_service"

  # MongoDB URIs
  MONGO_URI_EVENT: "bW9uZ29kYjovL21vbmdvX2V2ZW50OjI3MDE3Lw=="  # Base64-encoded "mongodb://mongo_event:27017/"
  MONGO_URI_NOTIFICATION: "bW9uZ29kYjovL21vbmdvX25vdGlmaWNhdGlvbjoyNzAxNy8="  # Base64-encoded "mongodb://mongo_notification:27017/"

  # Email Credentials
  EMAIL_USER: "ZGV2b3BzLnNoYWhtZWVyLmRhbmlzaEBnbWFpbC5jb20="  # Base64-encoded email
  EMAIL_PASS: "bHBheHV3dGVyZm1xaml4"  # Base64-encoded password

  # Email Credentials
  email_user: "ZGV2b3BzLnNoYWhtZWVyLmRhbmlzaEBnbWFpbC5jb20="  # Base64-encoded email
  email_pass: "bHBheHV3dGVyZm1xaml4"  # Base64-encoded password
