name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/*.cs'
      - '.github/workflows/**'
      - 'k8s/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and Push Docker Images
        run: |
          services=(frontend-mvc catalog-api basket-api orders-webjob)
          for svc in "${services[@]}"; do
            docker build -t houssemdocker/$svc:latest ./$svc
            docker push houssemdocker/$svc:latest
          done

      - name: Update k8s manifests image tag (optional if using `:latest`)
        run: |
          sed -i "s/:0.1/:latest/g" k8s/**/*.yaml

      - name: Commit updated manifests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add k8s/
          git commit -m "Update image tags to latest" || echo "No changes to commit"
          git push

      - name: Trigger ArgoCD Sync (optional)
        run: echo "ArgoCD will auto-sync from Git"
