name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '**/*.cs'
      - '*.yaml'  # changed from k8s/*.yaml to *.yaml

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker images
        run: |
          docker build -t houssemdocker/frontend-mvc:latest -f Frontend.Mvc/Dockerfile .
          docker push houssemdocker/frontend-mvc:latest

          docker build -t houssemdocker/catalog-api:latest -f Catalog.Api.Dockerfile .
          docker push houssemdocker/catalog-api:latest

          docker build -t houssemdocker/basket-api:latest -f Basket.Api.Dockerfile .
          docker push houssemdocker/basket-api:latest

      - name: Update YAML manifests with latest image tags
        run: |
          sed -i 's|image: .*/frontend-mvc:.*|image: houssemdocker/frontend-mvc:latest|' kubernetes-all-in-one.yaml
          sed -i 's|image: .*/catalog-api:.*|image: houssemdocker/catalog-api:latest|' kubernetes-all-in-one.yaml
          sed -i 's|image: .*/basket-api:.*|image: houssemdocker/basket-api:latest|' kubernetes-all-in-one.yaml

      - name: Commit updated manifests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.yaml
          git commit -m "Update deployment manifests with latest image tags" || echo "No changes to commit"
          git push
